version: "3.3"
services:
  dev-tf:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dev_tf
    restart: unless-stopped
    hostname: dev-tf
    # tty: true
    # stdin_open: true
    user: root
    # init: true
    working_dir: /root/
    privileged: true
    volumes:
      - type: bind
        source: ./
        target: /root/terraform
    command: /sbin/init